version: '3'
services:
  app:
    build: .
    volumes:
      - .:/project
    command: "jupyter notebook --allow-root"
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_PASSWORD=test123
    restart: "always"